manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    # --- 以下のリモートを追加  ---
    - name: victorlucachi
      url-base: https://github.com/victorlucachi
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    # --- 以下のCharybdisキーボードモジュールを追加  ---
    - name: zmk-keyboards-charybdis
      url: https://github.com/victorlucachi/zmk-keyboards-charybdis
      revision: main
      path: modules/zmk-keyboards-charybdis

  self:
    path: config
